---
- name: Get host os major version
  set_fact:
    rhel_major_version: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"

- name: Install common packages for RHEL 7 OS
  import_role:
    name: install-packages
  vars:
    install_packages_list: "{{ rhel7_packages }}"
  when: "{{ rhel_major_version }}" == "7"

- name: Install common packages for RHEL 8 OS
  import_role:
    name: install-packages
  vars:
    install_packages_list: "{{ all_packages }}"
  when: "{{ rhel_major_version }}" == "8"
